name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable'
      - name: format
        run: |
          nix fmt
          if [ -n "$(git status --porcelain)" ]; then
            echo "code not formatted. run:"
            echo "$ nix fmt"
            echo "$ git add ."
            echo "$ git commit --amend --no-edit"
            echo "$ git push --force"
            exit 1
          fi
  nix:
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - uses: actions/checkout@v5
      - name: install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable'
      - name: flake check
        run: nix flake check --all-systems
  rust:
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - uses: actions/checkout@v5
      - name: install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable'
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      - name: generate datasets
        run: nix build .#data -o lib/data
      - name: clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: tests
        run: cargo test --lib
  shell:
    runs-on: ubuntu-latest
    needs: formatting
    steps:
      - uses: actions/checkout@v5
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
  misc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: commit message
        run: |
          bash scripts/check-commit-message.sh "$(git log -1 --pretty=%B)"
