name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable'
      - name: set up cachix
        uses: cachix/cachix-action@v16
        with:
          name: nixdle
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: build
        run: nix build .#nixdle
  cargo:
    runs-on: ubuntu-latest
    needs: nix
    steps:
      - uses: actions/checkout@v6
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      - name: get crate version
        id: crate_version
        run: |
          VERSION="$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')"
          echo "CRATE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "crate_version=$VERSION" >> $GITHUB_OUTPUT
      - name: publish crates
        run: |
          cargo publish -p nixdle --token ${{ secrets.CRATES_TOKEN }}
  git:
    runs-on: ubuntu-latest
    needs: cargo
    steps:
      - uses: actions/checkout@v6
      - name: config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: update stable branch
        run: |
          git push origin "HEAD:stable" --force
      - name: gh release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
